### ISSUE TITLE
Broken DAG: [/app/dags/airflow_job_one_2.py] No module named 'dsutil'

### ISSUE THREAD

**Issue by Roylamer** [michaelchanwahyan/datalab#7]
HI ,

I have followed the instruction from set schedule but it keep showing the error  "No module named 'dsutil'"

**Comment by michaelchanwahyan** [comment]
hi Roylamer,
thanks for pointing out the error.
a quick workaround is to install the dutil package by using @IcarusSO 's branch
`pip3 install git+https://github.com/IcarusSO/dsutil.git`

i will soon distinguish the "Set Schedule" wiki into "Set Schedule - Airflow" and "Set Schedule - Cron".
the cause of missing out dustily is that "Airflow" is less stable and less responsive than cron.
using Airflow may encounter bugs that are more difficult to be fixed / avoided than using cron.

**Comment by Roylamer** [comment]
Thank you for your rapid response Micheal !

Merely install icarus's dsuil is not enough. You also need to 

pip3 install git+https://github.com/takluyver/nbparameterise.git

Then work like a charm !!!!! Thank you very much

**Comment by michaelchanwahyan** [comment]
hi Roylamer,

thanks for pointing out the nbparameterise.git.
as I remember, icarus's fork on nbparameterise is an enhanced version
https://github.com/IcarusSO/nbparameterise

you may try look into his "no timeout" changes at https://github.com/IcarusSO/nbparameterise/commit/61a99af0d90612364600a7bb936aadabb53ff902#diff-acd47f6d80b9518a46aa71d0a31e8705

Best
Michael

**Comment by Roylamer** [comment]
Thank u Micheal . I have used the takluyver version for nbparamterise and yes it has the timeout problem.  

I try to uninstall the nbparamterise and pip install+git  https://github.com/IcarusSO/nbparameterise. However, airflow will keep throwing out the error *module code_driver* unfounded.

**Comment by IcarusSO** [comment]
Hi Michael, I also find that it's a bit strange that 
1. I cannot uninstall the default nbparameterise and 
2. the airflow keep running after I terminate the airflow webserver screen

**Comment by Roylamer** [comment]
Hi Micheal,

Finally I have found the solution for nbparameterise.  I have forked the OG version of nbparameterise and modified the file according to Icarus veriosn. 

Then work like a charm and fix the time out problem! 

https://github.com/Roylamer/nbparameterise

**Comment by michaelchanwahyan** [comment]
hi @IcarusSO 

hi Icarus,

I'm able to perform the following

1)

freshly startup the datalab image, i am able to list out the three background services
`Tue Feb 19 14:34:58 HKT 2019
/
[root @ docker] $ screen -ls
There are screens on:
	43.scheduler	(02/19/19 14:34:59)	(Detached)
	40.airflow_webservice	(02/19/19 14:34:59)	(Detached)
	12.jupyter_lab	(02/19/19 14:34:57)	(Detached)
3 Sockets in /var/run/screen/S-root.

Tue Feb 19 14:35:01 HKT 2019
/
[root @ docker] $`

2)

the airflow is using port 9090 so that localhost:9090 is shown up in browser.

when i re-attach to airflow_webservice and terminate it, the webservice stops.

3)

when I attemp to show up all the pip-installed packages with 'nb', if see nbparameterise

`Tue Feb 19 14:35:01 HKT 2019
/
[root @ docker] $ pip3 freeze | grep nb
nbconvert==5.4.0
nbformat==4.4.0
nbparameterise==0.0.1
widgetsnbextension==3.4.2

Tue Feb 19 14:37:30 HKT 2019
/
[root @ docker] $`

4)

and i am able to uninstall it by

`Tue Feb 19 14:37:30 HKT 2019
/
[root @ docker] $ pip3 uninstall nbparameterise
Uninstalling nbparameterise-0.0.1:
  Would remove:
    /usr/local/lib/python3.6/dist-packages/nbparameterise-0.0.1.dist-info/*
    /usr/local/lib/python3.6/dist-packages/nbparameterise/*
Proceed (y/n)? y
  Successfully uninstalled nbparameterise-0.0.1

Tue Feb 19 14:38:34 HKT 2019
/
[root @ docker] $`

hope my above illustration helps solve your problems

**Comment by IcarusSO** [comment]
As I am promoting this docker can connect airflwo and jupyter in stackoverflow and I believe quite a number of users come from this reason. I will do some adjustment to make sure we are providing a easy solution to them. @michaelchanwahyan Let me know if you have any concerns
